"""biometria y sesiones

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-26 13:54:38.101774
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('face_distance', sa.Float(), nullable=True),
    sa.Column('brightness', sa.Float(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('location_source', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('province', sa.String(length=120), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_sessions_created_at'), 'login_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_login_sessions_identifier'), 'login_sessions', ['identifier'], unique=False)
    op.create_index(op.f('ix_login_sessions_user_id'), 'login_sessions', ['user_id'], unique=False)
    op.add_column('users', sa.Column('dni', sa.String(length=8), nullable=True))
    op.add_column('users', sa.Column('face_descriptors', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('photo', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('face_enrolled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('biometric_consent_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_dni'), 'users', ['dni'], unique=True)
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute('ALTER TABLE "login_sessions" ENABLE ROW LEVEL SECURITY')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_dni'), table_name='users')
    op.drop_column('users', 'biometric_consent_at')
    op.drop_column('users', 'face_enrolled_at')
    op.drop_column('users', 'photo')
    op.drop_column('users', 'face_descriptors')
    op.drop_column('users', 'dni')
    op.drop_index(op.f('ix_login_sessions_user_id'), table_name='login_sessions')
    op.drop_index(op.f('ix_login_sessions_identifier'), table_name='login_sessions')
    op.drop_index(op.f('ix_login_sessions_created_at'), table_name='login_sessions')
    op.drop_table('login_sessions')
    # ### end Alembic commands ###
